---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wren-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - wren.dev
  resources:
  - agentruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wren.dev
  resources:
  - agentruns/finalizers
  verbs:
  - update
- apiGroups:
  - wren.dev
  resources:
  - agentruns/status
  verbs:
  - get
  - patch
  - update
